### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by Lewiscowles1986** [Lewiscowles1986/ulid#1]
Needs Travis or other CI

**Comment by Lewiscowles1986** [comment]
Jenkins instructions added to code-base https://github.com/Lewiscowles1986/ulid/commit/e9f1011e99aafc2b663bf272b1d64214ddab7e6b

**Comment by Lewiscowles1986** [comment]
Note: open to travis etc instructions and PR, for now I'm happy enough with internal Jenkins

**Comment by peter279k** [comment]
CI integration is successful. The Travis CI build log is available [here](https://travis-ci.org/Lewiscowles1986/php-ulid/builds/403254668).

**Comment by Lewiscowles1986** [comment]
You're right @peter279k it's been there for some time.
