### ISSUE TITLE
Bug: 1.21e+24 per second

### ISSUE THREAD

**Issue by ViAndersson** [Lewiscowles1986/ulid#27]
Spec says implementations should allow 1.21e+24 ULIDs per **millisecond**.

This implementation allows  1.21e+24 per **second**, since it relies on `(int) microtime(true) * 1000` which truncates the decimal value before multiplication to milliseconds, resulting in only the seconds being present in the number.

This is easily fixed by changing the `public function getTime(): int` to return `intval(microtime(true) * 1000)` causing the value to be converted to integer after it has been multiplied.

Best regards.

**Comment by Lewiscowles1986** [comment]
1.21e+24
scientific e notation

1210000000000000000000000
(real number)

= one septillion two hundred ten sextillion
word form

from the golang implementation page
> 1.21e+24 unique ULIDs per millisecond (1,208,925,819,614,629,174,706,176 to be exact)

```
282, 366, 920, 938, 463, 463, 374, 607, 431, 768, 211, 455 max 128-bit value
                 1, 208, 925, 819, 614, 629, 174, 706, 176 max claimed per MS
                                   281, 474, 976, 710, 655 max unsigned 48-bit int (seconds part)
                           9, 223, 372, 036, 854, 775, 807 max PHP (64-bit) integer value
```

as ulid spec also says
> ## [Components](https://github.com/ulid/spec#components)
> ### Timestamp
> 
> #### 48 bit integer
> * UNIX-time in milliseconds
> * Won't run out of space 'til the year 10889 AD.
> 
> #### Randomness
> 
> * 80 bits
> * Cryptographically secure source of randomness, if possible

https://github.com/ulid/spec#:~:text=48%20bit%20integer,time%20in%20milliseconds

are you sure that the PHP integer cannot multiply by 1000?
If you are insistent, please also see https://3v4l.org/8GV7Y#veol

**Comment by ViAndersson** [comment]
You’re correct, I missed checking the code properly when testing. My bad (int) (time * 1000) is fine.
