### ISSUE TITLE
Allow user to supply own source of randomness

### ISSUE THREAD

**Issue by fieryprophet** [Lewiscowles1986/ulid#3]
Tying the finalized class to lcg_value() prevents utilizing cryptographically secure forms of randomization.

Something like the following:

`(new Ulid(new RandomBytesGenerator))->get();`
`//ULID with random_bytes() as source of randomness`

**Comment by Lewiscowles1986** [comment]
whilst I agree, it needs to be compatible with the other implementations of ULID. Happy to check over a PR :wink:

**Comment by fieryprophet** [comment]
If you're basing it off this implementation they don't specify a specific form of randomness, although they also recommend a cryptographically secure source if possible:

https://github.com/alizain/ulid

> Randomness
>    80 bits
>   Cryptographically secure source of randomness, if possible

**Comment by Lewiscowles1986** [comment]
Update https://github.com/Lewiscowles1986/ulid/commit/0898db814144ceb8dd36f1f9244e9b1ff06923fe

I've got some work to do on the repo. Time will also be DI for network time or whatever can be used. Not sure if it was before but this repo is now PHP7 only
